    <!-- BEGIN: Vendor JS-->
    <script src="/app-assets/vendors/js/vendors.min.js" defer></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="/app-assets/js/core/app-menu.js" defer></script>
    <script src="/app-assets/js/core/app.js" defer></script>
    <script src="/app-assets/js/scripts/components.js" defer></script>
    <script src="/app-assets/vendors/js/extensions/dropzone.min.js" defer></script>
    <script src="/app-assets/vendors/js/tables/datatable/datatables.min.js" defer></script>
    <script src="/app-assets/vendors/js/tables/datatable/datatables.buttons.min.js" defer></script>
    <script src="/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js" defer></script>
    <script src="/app-assets/vendors/js/tables/datatable/buttons.bootstrap.min.js" defer></script>
    <script src="/app-assets/vendors/js/tables/datatable/dataTables.select.min.js" defer></script>
    <script src="/app-assets/vendors/js/tables/datatable/datatables.checkboxes.min.js" defer></script>
    <script src="/app-assets/vendors/js/extensions/toastr.min.js" defer></script>
    <script src="/app-assets/js/scripts/ui/data-list-view.js" defer></script>
    <script src="/app-assets/vendors/js/charts/apexcharts.min.js" defer></script>
    <script src="/app-assets/vendors/js/extensions/tether.min.js" defer></script>
    <script src="/app-assets/vendors/js/extensions/shepherd.min.js" defer></script>
    <script src="/app-assets/js/scripts/pages/dashboard-analytics.js" defer></script>
